# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "solargraph"
gem "ruby-enum"
gem "ruby-debug-ide"
gem "debase"
gem "rspec"
gem "guard-rspec"
